// Avionic dots · Quickshell (https://quickshell.org), targets Quickshell 0.3.
// One bar per screen. Each theme has its own bar layout under themes/<name>/;
// Theme.qml (generated by scripts/apply-theme.sh from themes/<name>/palette.sh)
// says which one to draw. Shared pieces (tray, power, readouts, calendar,
// workspace switching, /proc stats) live in this directory.
//
// Reload from a script:  qs ipc call avionic reload
//@ pragma UseQApplication
import QtQuick
import Quickshell
import Quickshell.Io
import qs
import qs.themes.avionic as Avionic
import qs.themes.magma as Magma

ShellRoot {
    // Exactly one of these has screens; the other stays empty.
    Variants {
        model: Theme.bar === "avionic" ? Quickshell.screens : []

        Avionic.Bar {}
    }

    Variants {
        model: Theme.bar !== "avionic" ? Quickshell.screens : []

        Magma.Bar {}
    }

    IpcHandler {
        target: "avionic"

        function reload(): void {
            Quickshell.reload(false);
        }
    }
}
